### ISSUE TITLE
HW support

### ISSUE THREAD

**Issue by NYFB8888** [oelison/SmartGuide#1]
Hello
I have a few smartguids and would like to follow your steps to experiment with them.  I am unfamiliar with SM technology, therefore, I would appreciate if you could direct me on how to connect with the SM programmer.
Many thanks in advance
NYFB

**Comment by oelison** [comment]
Hi.
I use a ST-Link V2.
PIN 1 RST
PIN 2 SWIM
PIN 3 GND
PIN 4 3v3 as 3V a Bit high but working
When you have the Antenna on the bottom (Display readable upright) you have on the right side six straight solder points.
From bottom to top the first four are used.
1. GND 
2. 3v3
3. SWIM
4. RST
Later I will add this to the readme and add some pictures.

**Comment by NYFB8888** [comment]
Many thanks
